# Site settings
title: Jim's Test Netlify Site
email: jim@jimpick.com.com
description: > # this means to ignore newlines until "baseurl:"
  Testing Netlify
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://http://peon-deer-64037.netlify.com/" # the base hostname & protocol for your site
twitter_username: jimpick
github_username:  jimpick

# Build settings
markdown: kramdown
